name: Build Distributables
on:
  push:
    branches:
      - main
jobs:
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/github-actions
    - uses: actions/setup-node@master
      with:
        node-version: 18.18.2
    - name: install node tools
      run: npm install --global --production windows-build-tools@4.0.0
    - name: install node-gyp
      run: npm install --global node-gyp@latest
    - name: Set node config to use python2.7
      run: npm config set python python2.7
    - name: Set node config to set msvs_version to 2015
      run: npm config set msvs_version 2015
    - name: Work around for Windows Server 2019
      run: set path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
    - name: Install dependencies
      run: npm install
    - name: Build on Windows
      run: npm publish --target=win32 --arch=x64
    - name: see directory
      run: ls ./out/make
    # - uses: actions/upload-artifact@master
    #   with:
    #     name: windows-installer
    #     path: ./electron_dist/squirrel-windows/*
