name: Build Distributables
on:
  push:
    branches:
      - main
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
  
  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install appdmg
      run: npm install -g appdmg
    - name: install dependencies
      run: npm install
    - name: install appdmg
      run: npm install -g appdmg
    - name: build
      run: npm run make
  
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Install WiX Toolset
      run: choco install wixtoolset
    - name: Set up WiX Toolset
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $env:PATH
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
